bad_request: [Bad request, 400]
invalid_payload: [Invalid Payload, 400]
unauthorized: [Unauthorized, 401]
token_expired: [Token expired, 401]
invalid_token: [Invalid token, 401]
forbidden: [Forbidden, 403]
not_found: [Not found, 404]
conflict: [Conflict, 409]
internal: [Internal server error, 500]
missing_auth_header: ['Missing Authentication Header', 401]
