"""Initial startup

Revision ID: 806e5901953c
Revises: 
Create Date: 2026-05-19 12:12:31.779301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806e5901953c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('uid', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('subtitles_url', sa.Text(), nullable=True),
    sa.Column('output_title', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('target_filename', sa.String(length=255), nullable=False),
    sa.Column('target_plex_folder', sa.Text(), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=False),
    sa.Column('selected_streams', sa.JSON(), nullable=False),
    sa.Column('encoder_options', sa.JSON(), nullable=False),
    sa.Column('proxy_override', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('processed_time', sa.String(length=32), nullable=True),
    sa.Column('speed', sa.String(length=32), nullable=True),
    sa.Column('current_phase', sa.String(length=64), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('job_events',
    sa.Column('uid', sa.String(length=16), nullable=False),
    sa.Column('job_uid', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_uid'], ['download_jobs.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_events')
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
